#!/bin/bash

if [ $# -lt 1 ]; then
	echo "Not enough arguments provided."
	echo "Usage: $0 [user]"
	exit -1
fi

sed 's/$username/'$1'/g' /root/.bin/mksasl.ldif | ldapmodify -x -D cn=admin,dc=ee,dc=cooper,dc=edu -W
