#!/bin/bash
#awk -F, '/^[^#]/{print $3 " " $2 " " $2 ".ee.cooper.edu"}' /etc/dnsmasq.d/dhcp.hosts | cat /etc/hosts.local - | sudo tee /etc/hosts
awk -F, '/^[^#]/{print $3 "\t" $2 ".ee\t" $1 "\tnodhcp;"}' /etc/dnsmasq.d/dhcp.hosts | cut -c 8- > cucc-dns.out
